spring:
  datasource:
    name: test
    password: hot4el
    username: hotel
    url: jdbc:mysql://101.37.20.31:3306/test
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: utf-8
    excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html


server:
  port: 8080


mybatis:
  mapper-locations: com/mocha/mapper/*.xml
  type-aliases-package: com.mocha.bean


