spring:
  datasource:
    name: test
    password: hot4el
    username: hotel
    url: jdbc:mysql://101.37.20.31:3306/test
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: utf-8
    excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html


server:
  port: 8080

logging:
#  config: String
#  exception-conversion-word: String
  file: log.log
  level: info
#  path:
#  register-shutdown-hook: true



#mybatis:
#  mapper-locations: com/mocha/mapper/*.xml
#  type-aliases-package: com.mocha.bean


